package com.kyh.system.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import com.kyh.system.model.Syain;
import com.kyh.system.model.SyainExample;

public interface SyainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    long countByExample(SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    int deleteByExample(SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer syainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    int insert(Syain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    int insertSelective(Syain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    List<Syain> selectByExample(SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    Syain selectByPrimaryKey(Integer syainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Syain record, @Param("example") SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Syain record, @Param("example") SyainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Syain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table syain_main
     *s
     * @mbg.generated
     */
    int updateByPrimaryKey(Syain record);
    
    @Select("SELECT value1, category3 FROM tg_setting WHERE category1 = 3 and category2 = 6")
    List<String> getOSList();
    
    @Select("SELECT value1, category2 FROM tg_setting WHERE category1 = 1 and category3 = 1")
    List<Map<String, Object>> getCompanyNameList();
    
    @Select("SELECT value1, category3 FROM tg_setting WHERE category1 = 3 and category2 = 4")
    List<Map<String, Object>> getJobTypeList();
    
    List<Syain> getSyainList(int syozokuKaisya, String name, int syokugyoKind, boolean active, boolean inactive);
}