package com.kyh.system.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Syain {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.syain_id
     *
     * @mbg.generated
     */
    private Integer syainId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.first_name_kanji
     *
     * @mbg.generated
     */
    private String firstNameKanji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.last_name_kanji
     *
     * @mbg.generated
     */
    private String lastNameKanji;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.first_name_kana
     *
     * @mbg.generated
     */
    private String firstNameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.last_name_kana
     *
     * @mbg.generated
     */
    private String lastNameKana;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.first_name_eigo
     *
     * @mbg.generated
     */
    private String firstNameEigo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.last_name_eigo
     *
     * @mbg.generated
     */
    private String lastNameEigo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.seibetu
     *
     * @mbg.generated
     */
    private Integer seibetu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.tanjyobi
     *
     * @mbg.generated
     */
    private Date tanjyobi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.kokuseki
     *
     * @mbg.generated
     */
    private Integer kokuseki;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.syussinn
     *
     * @mbg.generated
     */
    private String syussinn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.haigusya
     *
     * @mbg.generated
     */
    private Integer haigusya;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.passport_num
     *
     * @mbg.generated
     */
    private String passportNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.passport_end_date
     *
     * @mbg.generated
     */
    private Date passportEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.visa_kikan
     *
     * @mbg.generated
     */
    private Integer visaKikan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.visa_end_date
     *
     * @mbg.generated
     */
    private Date visaEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.zairyu_sikaku
     *
     * @mbg.generated
     */
    private Integer zairyuSikaku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.kojin_num
     *
     * @mbg.generated
     */
    private String kojinNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.zairyu_num
     *
     * @mbg.generated
     */
    private String zairyuNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.syozoku_kaisya
     *
     * @mbg.generated
     */
    private Integer syozokuKaisya;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.nyuusya_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date nyuusyaDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.taisya_date
     *
     * @mbg.generated
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    @JsonFormat(pattern = "yyyy-MM-dd")
    private Date taisyaDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.syokugyo_kind
     *
     * @mbg.generated
     */
    private Integer syokugyoKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.rainiti_date
     *
     * @mbg.generated
     */
    private Date rainitiDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.bikou
     *
     * @mbg.generated
     */
    private String bikou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.yuubin
     *
     * @mbg.generated
     */
    private String yuubin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.jyusyo_1
     *
     * @mbg.generated
     */
    private String jyusyo1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.jyusyo_2
     *
     * @mbg.generated
     */
    private String jyusyo2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.moyori_eki
     *
     * @mbg.generated
     */
    private String moyoriEki;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.tel
     *
     * @mbg.generated
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.wechat
     *
     * @mbg.generated
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.line
     *
     * @mbg.generated
     */
    private String line;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.bokoku_jyusyo
     *
     * @mbg.generated
     */
    private String bokokuJyusyo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.bokoku_kinnkyuu_rennraku
     *
     * @mbg.generated
     */
    private String bokokuKinnkyuuRennraku;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.saisyuu_gakureki
     *
     * @mbg.generated
     */
    private Integer saisyuuGakureki;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.gakkou_name
     *
     * @mbg.generated
     */
    private String gakkouName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.sennmom_name
     *
     * @mbg.generated
     */
    private String sennmomName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.sotugyo_date
     *
     * @mbg.generated
     */
    private Date sotugyoDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.gyumu_nensu
     *
     * @mbg.generated
     */
    private Float gyumuNensu;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.it_os
     *
     * @mbg.generated
     */
    private String itOs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.it_gengo
     *
     * @mbg.generated
     */
    private String itGengo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.it_db
     *
     * @mbg.generated
     */
    private String itDb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.it_web_server
     *
     * @mbg.generated
     */
    private String itWebServer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.it_fw
     *
     * @mbg.generated
     */
    private String itFw;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.it_other
     *
     * @mbg.generated
     */
    private String itOther;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.it_bikou
     *
     * @mbg.generated
     */
    private String itBikou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.delete_flag
     *
     * @mbg.generated
     */
    private Integer deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.tourokubi
     *
     * @mbg.generated
     */
    private Date tourokubi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column syain_main.kousinnbi
     *
     * @mbg.generated
     */
    private Date kousinnbi;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.syain_id
     *
     * @return the value of syain_main.syain_id
     *
     * @mbg.generated
     */
    public Integer getSyainId() {
        return syainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.syain_id
     *
     * @param syainId the value for syain_main.syain_id
     *
     * @mbg.generated
     */
    public void setSyainId(Integer syainId) {
        this.syainId = syainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.first_name_kanji
     *
     * @return the value of syain_main.first_name_kanji
     *
     * @mbg.generated
     */
    public String getFirstNameKanji() {
        return firstNameKanji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.first_name_kanji
     *
     * @param firstNameKanji the value for syain_main.first_name_kanji
     *
     * @mbg.generated
     */
    public void setFirstNameKanji(String firstNameKanji) {
        this.firstNameKanji = firstNameKanji == null ? null : firstNameKanji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.last_name_kanji
     *
     * @return the value of syain_main.last_name_kanji
     *
     * @mbg.generated
     */
    public String getLastNameKanji() {
        return lastNameKanji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.last_name_kanji
     *
     * @param lastNameKanji the value for syain_main.last_name_kanji
     *
     * @mbg.generated
     */
    public void setLastNameKanji(String lastNameKanji) {
        this.lastNameKanji = lastNameKanji == null ? null : lastNameKanji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.first_name_kana
     *
     * @return the value of syain_main.first_name_kana
     *
     * @mbg.generated
     */
    public String getFirstNameKana() {
        return firstNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.first_name_kana
     *
     * @param firstNameKana the value for syain_main.first_name_kana
     *
     * @mbg.generated
     */
    public void setFirstNameKana(String firstNameKana) {
        this.firstNameKana = firstNameKana == null ? null : firstNameKana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.last_name_kana
     *
     * @return the value of syain_main.last_name_kana
     *
     * @mbg.generated
     */
    public String getLastNameKana() {
        return lastNameKana;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.last_name_kana
     *
     * @param lastNameKana the value for syain_main.last_name_kana
     *
     * @mbg.generated
     */
    public void setLastNameKana(String lastNameKana) {
        this.lastNameKana = lastNameKana == null ? null : lastNameKana.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.first_name_eigo
     *
     * @return the value of syain_main.first_name_eigo
     *
     * @mbg.generated
     */
    public String getFirstNameEigo() {
        return firstNameEigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.first_name_eigo
     *
     * @param firstNameEigo the value for syain_main.first_name_eigo
     *
     * @mbg.generated
     */
    public void setFirstNameEigo(String firstNameEigo) {
        this.firstNameEigo = firstNameEigo == null ? null : firstNameEigo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.last_name_eigo
     *
     * @return the value of syain_main.last_name_eigo
     *
     * @mbg.generated
     */
    public String getLastNameEigo() {
        return lastNameEigo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.last_name_eigo
     *
     * @param lastNameEigo the value for syain_main.last_name_eigo
     *
     * @mbg.generated
     */
    public void setLastNameEigo(String lastNameEigo) {
        this.lastNameEigo = lastNameEigo == null ? null : lastNameEigo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.seibetu
     *
     * @return the value of syain_main.seibetu
     *
     * @mbg.generated
     */
    public Integer getSeibetu() {
        return seibetu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.seibetu
     *
     * @param seibetu the value for syain_main.seibetu
     *
     * @mbg.generated
     */
    public void setSeibetu(Integer seibetu) {
        this.seibetu = seibetu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.tanjyobi
     *
     * @return the value of syain_main.tanjyobi
     *
     * @mbg.generated
     */
    public Date getTanjyobi() {
        return tanjyobi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.tanjyobi
     *
     * @param tanjyobi the value for syain_main.tanjyobi
     *
     * @mbg.generated
     */
    public void setTanjyobi(Date tanjyobi) {
        this.tanjyobi = tanjyobi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.kokuseki
     *
     * @return the value of syain_main.kokuseki
     *
     * @mbg.generated
     */
    public Integer getKokuseki() {
        return kokuseki;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.kokuseki
     *
     * @param kokuseki the value for syain_main.kokuseki
     *
     * @mbg.generated
     */
    public void setKokuseki(Integer kokuseki) {
        this.kokuseki = kokuseki;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.syussinn
     *
     * @return the value of syain_main.syussinn
     *
     * @mbg.generated
     */
    public String getSyussinn() {
        return syussinn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.syussinn
     *
     * @param syussinn the value for syain_main.syussinn
     *
     * @mbg.generated
     */
    public void setSyussinn(String syussinn) {
        this.syussinn = syussinn == null ? null : syussinn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.haigusya
     *
     * @return the value of syain_main.haigusya
     *
     * @mbg.generated
     */
    public Integer getHaigusya() {
        return haigusya;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.haigusya
     *
     * @param haigusya the value for syain_main.haigusya
     *
     * @mbg.generated
     */
    public void setHaigusya(Integer haigusya) {
        this.haigusya = haigusya;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.passport_num
     *
     * @return the value of syain_main.passport_num
     *
     * @mbg.generated
     */
    public String getPassportNum() {
        return passportNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.passport_num
     *
     * @param passportNum the value for syain_main.passport_num
     *
     * @mbg.generated
     */
    public void setPassportNum(String passportNum) {
        this.passportNum = passportNum == null ? null : passportNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.passport_end_date
     *
     * @return the value of syain_main.passport_end_date
     *
     * @mbg.generated
     */
    public Date getPassportEndDate() {
        return passportEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.passport_end_date
     *
     * @param passportEndDate the value for syain_main.passport_end_date
     *
     * @mbg.generated
     */
    public void setPassportEndDate(Date passportEndDate) {
        this.passportEndDate = passportEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.visa_kikan
     *
     * @return the value of syain_main.visa_kikan
     *
     * @mbg.generated
     */
    public Integer getVisaKikan() {
        return visaKikan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.visa_kikan
     *
     * @param visaKikan the value for syain_main.visa_kikan
     *
     * @mbg.generated
     */
    public void setVisaKikan(Integer visaKikan) {
        this.visaKikan = visaKikan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.visa_end_date
     *
     * @return the value of syain_main.visa_end_date
     *
     * @mbg.generated
     */
    public Date getVisaEndDate() {
        return visaEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.visa_end_date
     *
     * @param visaEndDate the value for syain_main.visa_end_date
     *
     * @mbg.generated
     */
    public void setVisaEndDate(Date visaEndDate) {
        this.visaEndDate = visaEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.zairyu_sikaku
     *
     * @return the value of syain_main.zairyu_sikaku
     *
     * @mbg.generated
     */
    public Integer getZairyuSikaku() {
        return zairyuSikaku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.zairyu_sikaku
     *
     * @param zairyuSikaku the value for syain_main.zairyu_sikaku
     *
     * @mbg.generated
     */
    public void setZairyuSikaku(Integer zairyuSikaku) {
        this.zairyuSikaku = zairyuSikaku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.kojin_num
     *
     * @return the value of syain_main.kojin_num
     *
     * @mbg.generated
     */
    public String getKojinNum() {
        return kojinNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.kojin_num
     *
     * @param kojinNum the value for syain_main.kojin_num
     *
     * @mbg.generated
     */
    public void setKojinNum(String kojinNum) {
        this.kojinNum = kojinNum == null ? null : kojinNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.zairyu_num
     *
     * @return the value of syain_main.zairyu_num
     *
     * @mbg.generated
     */
    public String getZairyuNum() {
        return zairyuNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.zairyu_num
     *
     * @param zairyuNum the value for syain_main.zairyu_num
     *
     * @mbg.generated
     */
    public void setZairyuNum(String zairyuNum) {
        this.zairyuNum = zairyuNum == null ? null : zairyuNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.syozoku_kaisya
     *
     * @return the value of syain_main.syozoku_kaisya
     *
     * @mbg.generated
     */
    public Integer getSyozokuKaisya() {
        return syozokuKaisya;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.syozoku_kaisya
     *
     * @param syozokuKaisya the value for syain_main.syozoku_kaisya
     *
     * @mbg.generated
     */
    public void setSyozokuKaisya(Integer syozokuKaisya) {
        this.syozokuKaisya = syozokuKaisya;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.nyuusya_date
     *
     * @return the value of syain_main.nyuusya_date
     *
     * @mbg.generated
     */
    public Date getNyuusyaDate() {
        return nyuusyaDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.nyuusya_date
     *
     * @param nyuusyaDate the value for syain_main.nyuusya_date
     *
     * @mbg.generated
     */
    public void setNyuusyaDate(Date nyuusyaDate) {
        this.nyuusyaDate = nyuusyaDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.taisya_date
     *
     * @return the value of syain_main.taisya_date
     *
     * @mbg.generated
     */
    public Date getTaisyaDate() {
        return taisyaDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.taisya_date
     *
     * @param taisyaDate the value for syain_main.taisya_date
     *
     * @mbg.generated
     */
    public void setTaisyaDate(Date taisyaDate) {
        this.taisyaDate = taisyaDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.syokugyo_kind
     *
     * @return the value of syain_main.syokugyo_kind
     *
     * @mbg.generated
     */
    public Integer getSyokugyoKind() {
        return syokugyoKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.syokugyo_kind
     *
     * @param syokugyoKind the value for syain_main.syokugyo_kind
     *
     * @mbg.generated
     */
    public void setSyokugyoKind(Integer syokugyoKind) {
        this.syokugyoKind = syokugyoKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.rainiti_date
     *
     * @return the value of syain_main.rainiti_date
     *
     * @mbg.generated
     */
    public Date getRainitiDate() {
        return rainitiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.rainiti_date
     *
     * @param rainitiDate the value for syain_main.rainiti_date
     *
     * @mbg.generated
     */
    public void setRainitiDate(Date rainitiDate) {
        this.rainitiDate = rainitiDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.bikou
     *
     * @return the value of syain_main.bikou
     *
     * @mbg.generated
     */
    public String getBikou() {
        return bikou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.bikou
     *
     * @param bikou the value for syain_main.bikou
     *
     * @mbg.generated
     */
    public void setBikou(String bikou) {
        this.bikou = bikou == null ? null : bikou.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.yuubin
     *
     * @return the value of syain_main.yuubin
     *
     * @mbg.generated
     */
    public String getYuubin() {
        return yuubin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.yuubin
     *
     * @param yuubin the value for syain_main.yuubin
     *
     * @mbg.generated
     */
    public void setYuubin(String yuubin) {
        this.yuubin = yuubin == null ? null : yuubin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.jyusyo_1
     *
     * @return the value of syain_main.jyusyo_1
     *
     * @mbg.generated
     */
    public String getJyusyo1() {
        return jyusyo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.jyusyo_1
     *
     * @param jyusyo1 the value for syain_main.jyusyo_1
     *
     * @mbg.generated
     */
    public void setJyusyo1(String jyusyo1) {
        this.jyusyo1 = jyusyo1 == null ? null : jyusyo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.jyusyo_2
     *
     * @return the value of syain_main.jyusyo_2
     *
     * @mbg.generated
     */
    public String getJyusyo2() {
        return jyusyo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.jyusyo_2
     *
     * @param jyusyo2 the value for syain_main.jyusyo_2
     *
     * @mbg.generated
     */
    public void setJyusyo2(String jyusyo2) {
        this.jyusyo2 = jyusyo2 == null ? null : jyusyo2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.moyori_eki
     *
     * @return the value of syain_main.moyori_eki
     *
     * @mbg.generated
     */
    public String getMoyoriEki() {
        return moyoriEki;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.moyori_eki
     *
     * @param moyoriEki the value for syain_main.moyori_eki
     *
     * @mbg.generated
     */
    public void setMoyoriEki(String moyoriEki) {
        this.moyoriEki = moyoriEki == null ? null : moyoriEki.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.tel
     *
     * @return the value of syain_main.tel
     *
     * @mbg.generated
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.tel
     *
     * @param tel the value for syain_main.tel
     *
     * @mbg.generated
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.email
     *
     * @return the value of syain_main.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.email
     *
     * @param email the value for syain_main.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.wechat
     *
     * @return the value of syain_main.wechat
     *
     * @mbg.generated
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.wechat
     *
     * @param wechat the value for syain_main.wechat
     *
     * @mbg.generated
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.line
     *
     * @return the value of syain_main.line
     *
     * @mbg.generated
     */
    public String getLine() {
        return line;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.line
     *
     * @param line the value for syain_main.line
     *
     * @mbg.generated
     */
    public void setLine(String line) {
        this.line = line == null ? null : line.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.bokoku_jyusyo
     *
     * @return the value of syain_main.bokoku_jyusyo
     *
     * @mbg.generated
     */
    public String getBokokuJyusyo() {
        return bokokuJyusyo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.bokoku_jyusyo
     *
     * @param bokokuJyusyo the value for syain_main.bokoku_jyusyo
     *
     * @mbg.generated
     */
    public void setBokokuJyusyo(String bokokuJyusyo) {
        this.bokokuJyusyo = bokokuJyusyo == null ? null : bokokuJyusyo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.bokoku_kinnkyuu_rennraku
     *
     * @return the value of syain_main.bokoku_kinnkyuu_rennraku
     *
     * @mbg.generated
     */
    public String getBokokuKinnkyuuRennraku() {
        return bokokuKinnkyuuRennraku;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.bokoku_kinnkyuu_rennraku
     *
     * @param bokokuKinnkyuuRennraku the value for syain_main.bokoku_kinnkyuu_rennraku
     *
     * @mbg.generated
     */
    public void setBokokuKinnkyuuRennraku(String bokokuKinnkyuuRennraku) {
        this.bokokuKinnkyuuRennraku = bokokuKinnkyuuRennraku == null ? null : bokokuKinnkyuuRennraku.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.saisyuu_gakureki
     *
     * @return the value of syain_main.saisyuu_gakureki
     *
     * @mbg.generated
     */
    public Integer getSaisyuuGakureki() {
        return saisyuuGakureki;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.saisyuu_gakureki
     *
     * @param saisyuuGakureki the value for syain_main.saisyuu_gakureki
     *
     * @mbg.generated
     */
    public void setSaisyuuGakureki(Integer saisyuuGakureki) {
        this.saisyuuGakureki = saisyuuGakureki;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.gakkou_name
     *
     * @return the value of syain_main.gakkou_name
     *
     * @mbg.generated
     */
    public String getGakkouName() {
        return gakkouName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.gakkou_name
     *
     * @param gakkouName the value for syain_main.gakkou_name
     *
     * @mbg.generated
     */
    public void setGakkouName(String gakkouName) {
        this.gakkouName = gakkouName == null ? null : gakkouName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.sennmom_name
     *
     * @return the value of syain_main.sennmom_name
     *
     * @mbg.generated
     */
    public String getSennmomName() {
        return sennmomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.sennmom_name
     *
     * @param sennmomName the value for syain_main.sennmom_name
     *
     * @mbg.generated
     */
    public void setSennmomName(String sennmomName) {
        this.sennmomName = sennmomName == null ? null : sennmomName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.sotugyo_date
     *
     * @return the value of syain_main.sotugyo_date
     *
     * @mbg.generated
     */
    public Date getSotugyoDate() {
        return sotugyoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.sotugyo_date
     *
     * @param sotugyoDate the value for syain_main.sotugyo_date
     *
     * @mbg.generated
     */
    public void setSotugyoDate(Date sotugyoDate) {
        this.sotugyoDate = sotugyoDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.gyumu_nensu
     *
     * @return the value of syain_main.gyumu_nensu
     *
     * @mbg.generated
     */
    public Float getGyumuNensu() {
        return gyumuNensu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.gyumu_nensu
     *
     * @param gyumuNensu the value for syain_main.gyumu_nensu
     *
     * @mbg.generated
     */
    public void setGyumuNensu(Float gyumuNensu) {
        this.gyumuNensu = gyumuNensu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.it_os
     *
     * @return the value of syain_main.it_os
     *
     * @mbg.generated
     */
    public String getItOs() {
        return itOs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.it_os
     *
     * @param itOs the value for syain_main.it_os
     *
     * @mbg.generated
     */
    public void setItOs(String itOs) {
        this.itOs = itOs == null ? null : itOs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.it_gengo
     *
     * @return the value of syain_main.it_gengo
     *
     * @mbg.generated
     */
    public String getItGengo() {
        return itGengo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.it_gengo
     *
     * @param itGengo the value for syain_main.it_gengo
     *
     * @mbg.generated
     */
    public void setItGengo(String itGengo) {
        this.itGengo = itGengo == null ? null : itGengo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.it_db
     *
     * @return the value of syain_main.it_db
     *
     * @mbg.generated
     */
    public String getItDb() {
        return itDb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.it_db
     *
     * @param itDb the value for syain_main.it_db
     *
     * @mbg.generated
     */
    public void setItDb(String itDb) {
        this.itDb = itDb == null ? null : itDb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.it_web_server
     *
     * @return the value of syain_main.it_web_server
     *
     * @mbg.generated
     */
    public String getItWebServer() {
        return itWebServer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.it_web_server
     *
     * @param itWebServer the value for syain_main.it_web_server
     *
     * @mbg.generated
     */
    public void setItWebServer(String itWebServer) {
        this.itWebServer = itWebServer == null ? null : itWebServer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.it_fw
     *
     * @return the value of syain_main.it_fw
     *
     * @mbg.generated
     */
    public String getItFw() {
        return itFw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.it_fw
     *
     * @param itFw the value for syain_main.it_fw
     *
     * @mbg.generated
     */
    public void setItFw(String itFw) {
        this.itFw = itFw == null ? null : itFw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.it_other
     *
     * @return the value of syain_main.it_other
     *
     * @mbg.generated
     */
    public String getItOther() {
        return itOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.it_other
     *
     * @param itOther the value for syain_main.it_other
     *
     * @mbg.generated
     */
    public void setItOther(String itOther) {
        this.itOther = itOther == null ? null : itOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.it_bikou
     *
     * @return the value of syain_main.it_bikou
     *
     * @mbg.generated
     */
    public String getItBikou() {
        return itBikou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.it_bikou
     *
     * @param itBikou the value for syain_main.it_bikou
     *
     * @mbg.generated
     */
    public void setItBikou(String itBikou) {
        this.itBikou = itBikou == null ? null : itBikou.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.delete_flag
     *
     * @return the value of syain_main.delete_flag
     *
     * @mbg.generated
     */
    public Integer getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.delete_flag
     *
     * @param deleteFlag the value for syain_main.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(Integer deleteFlag) {
        this.deleteFlag = deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.tourokubi
     *
     * @return the value of syain_main.tourokubi
     *
     * @mbg.generated
     */
    public Date getTourokubi() {
        return tourokubi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.tourokubi
     *
     * @param tourokubi the value for syain_main.tourokubi
     *
     * @mbg.generated
     */
    public void setTourokubi(Date tourokubi) {
        this.tourokubi = tourokubi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column syain_main.kousinnbi
     *
     * @return the value of syain_main.kousinnbi
     *
     * @mbg.generated
     */
    public Date getKousinnbi() {
        return kousinnbi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column syain_main.kousinnbi
     *
     * @param kousinnbi the value for syain_main.kousinnbi
     *
     * @mbg.generated
     */
    public void setKousinnbi(Date kousinnbi) {
        this.kousinnbi = kousinnbi;
    }
}